"""create emails and audio_clips tables

Revision ID: 6cb61c9efe9a
Revises: 
Create Date: 2026-08-20 23:51:54.217165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb61c9efe9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_user_id'), ['user_id'], unique=False)

    op.create_table('audio_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='audioclipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_clips_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_clips_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_clips_id'))
        batch_op.drop_index(batch_op.f('ix_audio_clips_email_id'))

    op.drop_table('audio_clips')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_user_id'))
        batch_op.drop_index(batch_op.f('ix_emails_sender'))
        batch_op.drop_index(batch_op.f('ix_emails_id'))

    op.drop_table('emails')
    # ### end Alembic commands ###
